/**
 * ops/scrub-env-check.ts - proof for order R1-env-scrub (2026-10-06).
 *
 * Checks the REAL src/company/scrubEnv.ts and the REAL launcher text produced by
 * src/company/fleet.ts (launcherScript), against a THROWAWAY COMPANY_ROOT and FLEET_REPO in the
 * OS temp directory. The live company/ tree and the repository's own .env are never touched, and
 * no network call is made: the only subprocess is a local, non-interactive PowerShell that runs
 * the generated scrub lines against fake values.
 *
 * Every fake value below is invented. process.env is snapshotted first and restored in a finally
 * block, so this harness ends with exactly the environment it started with.
 *
 *   npx tsx ops/scrub-env-check.ts
 *
 * Prints PASS or FAIL per line; exit code is 1 if any line is FAIL.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { launcherScrubLines, scrubList } from "../src/company/scrubEnv.js";
import type { FleetOrder, WorkOrder } from "../src/company/fleet.js";

// Fake, secret-looking values. Nothing here is a real credential.
const FAKE: Record<string, string> = {
  GITHUB_TOKEN: "ghp" + "_R1SCRUB_FAKE_0000000000",
  COMPANY_AUTH_TOKEN: "company_auth_FAKE_1111111111",
  SLACK_SIGNING_SECRET: "slack_signing_FAKE_2222222222",
  SESSION_SECRET: "session_secret_FAKE_3333333333",
  DB_PASSWORD: "db_password_FAKE_4444444444",
  MY_EXTRA_TOKEN: "extra_token_FAKE_5555555555",
  OPENCODE_STUB_API_KEY: "sk" + "-opencode-FAKE-6666666666",
  DEEPSEEK_API_KEY: "sk" + "-deepseek-FAKE-7777777777",
  ANTHROPIC_STUB_KEY: "sk" + "-ant-FAKE-8888888888",
};
const FAKE_VALUES = Object.values(FAKE);

let failures = 0;
function check(label: string, ok: boolean, detail = ""): void {
  if (!ok) failures++;
  console.log(`${ok ? "PASS" : "FAIL"} ${label}${detail ? `  -> ${detail}` : ""}`);
}

/** Set every key of `before` and drop everything that is not in it. */
function restoreEnv(before: NodeJS.ProcessEnv): void {
  for (const key of Object.keys(process.env)) if (!(key in before)) delete process.env[key];
  for (const [key, value] of Object.entries(before)) process.env[key] = value;
}

const envBefore: NodeJS.ProcessEnv = { ...process.env };
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "scrub-env-check-"));
const repoDir = path.join(dir, "repo");

type LauncherScript = (order: FleetOrder, wo: WorkOrder) => Promise<string>;

/** Write the launcher into the temp tree and return its text. */
async function launcherText(launcherScript: LauncherScript): Promise<string> {
  const order = { id: "R1CHECK" } as unknown as FleetOrder;
  const wo = { id: "WO1" } as unknown as WorkOrder;
  const file = await launcherScript(order, wo);
  return fs.readFileSync(file, "utf8");
}

try {
  fs.mkdirSync(repoDir, { recursive: true });
  process.env.MOCK_MODE = "1";
  process.env.COMPANY_ROOT = path.join(dir, "company");
  process.env.FLEET_REPO = repoDir;
  process.env.FLEET_PROVIDER = "opencode-go";
  delete process.env.FLEET_SCRUB_ENV;
  delete process.env.FLEET_SCRUB_EXTRA;
  for (const [k, v] of Object.entries(FAKE)) process.env[k] = v;

  const fleet = await import("../src/company/fleet.js");
  const repo = path.resolve(repoDir);
  const single = (s: string) => `'${s.replace(/'/g, "''")}'`;
  // The launcher this file produced BEFORE this order: header, title, cwd, jcode start.
  const preChangeLauncher = [
    "# fleet worker launcher (generated by src/company/fleet.ts)",
    `$Host.UI.RawUI.WindowTitle = 'fleet R1CHECK/WO1'`,
    `Set-Location -LiteralPath ${single(repo)}`,
    `jcode -p opencode-go`,
    "",
  ].join("\r\n");

  // 1. OFF by default: no scrub lines are emitted and the launcher text is byte-for-byte the
  //    pre-change template.
  const offLines = launcherScrubLines("powershell");
  const offText = await launcherText(fleet.launcherScript);
  check(
    "off by default: launcherScrubLines emits nothing and the launcher text is unchanged",
    offLines.length === 0 && offText === preChangeLauncher,
    `lines=${offLines.length}; identical=${offText === preChangeLauncher}; marker=${offText.includes("env-scrub")}`,
  );

  // 2. ON: the launcher really clears GITHUB_TOKEN, COMPANY_AUTH_TOKEN and *_SECRET/_PASSWORD names.
  process.env.FLEET_SCRUB_ENV = "1";
  const onLines = launcherScrubLines("powershell");
  const onText = await launcherText(fleet.launcherScript);
  const clears = (name: string) => onLines.some((l) => l.includes(`Env:${name}`));
  check(
    "on: the launcher clears GITHUB_TOKEN, COMPANY_AUTH_TOKEN and a *_SECRET + *_PASSWORD name",
    clears("GITHUB_TOKEN") && clears("COMPANY_AUTH_TOKEN") && clears("SLACK_SIGNING_SECRET") &&
      clears("SESSION_SECRET") && clears("DB_PASSWORD"),
    `lines=${onLines.length}`,
  );
  check(
    "on: every scrub line is present in the generated launcher, before jcode starts",
    onLines.length > 0 && onLines.every((l) => onText.includes(l)) &&
      onText.indexOf(onLines[0]) < onText.indexOf("jcode -p "),
    `first scrub line at ${onText.indexOf(onLines[0])}, jcode at ${onText.indexOf("jcode -p ")}`,
  );
  check(
    "on: deleting the scrub lines from the launcher leaves exactly the pre-change text",
    onText.split("\r\n").filter((l) => !onLines.includes(l)).join("\r\n") === preChangeLauncher,
  );

  // 3. Provider keys are never on the list, even though every one of them is set in this env.
  const providerKeys = ["OPENCODE_STUB_API_KEY", "DEEPSEEK_API_KEY", "ANTHROPIC_STUB_KEY"];
  const listed = scrubList();
  const providerOnList = providerKeys.filter((k) => listed.includes(k));
  const providerInText = providerKeys.filter((k) => onText.includes(k));
  check(
    "provider keys a jcode terminal may need are never in the list or the launcher",
    providerOnList.length === 0 && providerInText.length === 0,
    providerOnList.length || providerInText.length
      ? `listed=${JSON.stringify(providerOnList)} text=${JSON.stringify(providerInText)}`
      : `checked ${providerKeys.join(", ")}`,
  );

  // 4. FLEET_SCRUB_EXTRA adds names (with blanks/trailing comma tolerated), and a provider key
  //    named there is still refused.
  process.env.FLEET_SCRUB_EXTRA = " MY_EXTRA_TOKEN , ANTHROPIC_STUB_KEY ,";
  const extraLines = launcherScrubLines("powershell");
  check(
    "FLEET_SCRUB_EXTRA adds names, and cannot force a provider key onto the list",
    extraLines.some((l) => l.includes("Env:MY_EXTRA_TOKEN")) &&
      !extraLines.some((l) => l.includes("Env:ANTHROPIC_STUB_KEY")) &&
      !scrubList().includes("ANTHROPIC_STUB_KEY"),
    `lines=${extraLines.length}`,
  );

  // 5. Names only, never a value: no fake value appears in the emitted lines, the printed names
  //    line, or the launcher text.
  const printed = extraLines.find((l) => l.includes("cleared")) ?? "";
  const valueLeaks = FAKE_VALUES.filter((v) => extraLines.join("\n").includes(v) || onText.includes(v));
  check(
    "generated lines contain no value from the fake environment",
    valueLeaks.length === 0 && !onText.includes(FAKE.SESSION_SECRET) && printed.includes("MY_EXTRA_TOKEN"),
    valueLeaks.length ? `leaked=${JSON.stringify(valueLeaks)}` : `printed=${printed}`,
  );

  // 6. Run the generated lines in a real child PowerShell: the fake secrets really end up empty
  //    while the provider-style variables survive with their value.
  const reporter = (name: string) =>
    `Write-Output ('SCRUB|${name}|present=' + (Test-Path Env:${name}) + '|value=[' + $env:${name} + ']')`;
  const watched = [
    "GITHUB_TOKEN", "COMPANY_AUTH_TOKEN", "SLACK_SIGNING_SECRET", "SESSION_SECRET",
    "DB_PASSWORD", "MY_EXTRA_TOKEN", "OPENCODE_STUB_API_KEY", "DEEPSEEK_API_KEY",
  ];
  const psFile = path.join(dir, "scrub-run.ps1");
  fs.writeFileSync(psFile, [...extraLines, ...watched.map(reporter), ""].join("\r\n"), "utf8");
  const run = spawnSync(
    "powershell",
    ["-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", psFile],
    { encoding: "utf8", env: { ...process.env }, timeout: 30000 },
  );
  const out = `${run.stdout ?? ""}`;
  const report = (name: string): { present: boolean; value: string } | null => {
    const line = out.split(/\r?\n/).find((l) => l.startsWith(`SCRUB|${name}|`));
    if (!line) return null;
    const m = line.match(/value=\[(.*)\]\s*$/);
    return { present: /present=True/i.test(line), value: m ? m[1] : "" };
  };
  const scrubbed = watched.slice(0, 6).map((n) => [n, report(n)] as const);
  const survivors = watched.slice(6).map((n) => [n, report(n)] as const);
  check(
    "child PowerShell really leaves the denied variables empty",
    run.status === 0 &&
      scrubbed.every(([, r]) => r !== null && !r.present && r.value === ""),
    `exit=${run.status}; ${scrubbed.map(([n, r]) => `${n}=${r ? (r.present ? r.value : "empty") : "missing"}`).join(", ")}${run.stderr ? `; stderr: ${String(run.stderr).trim().slice(0, 200)}` : ""}`,
  );
  check(
    "child PowerShell keeps the provider-style variables",
    survivors.every(([n, r]) => r !== null && r.present && r.value === FAKE[n]),
    survivors.map(([n, r]) => `${n}=${r ? (r.present ? "present" : "GONE") : "missing"}`).join(", "),
  );
} catch (e) {
  check("harness completed without throwing", false, String(e instanceof Error ? e.message : e));
} finally {
  restoreEnv(envBefore);
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch {
    /* best effort: the temp dir is outside the repo */
  }
}

console.log(failures === 0 ? "scrub-env-check: all checks passed" : `scrub-env-check: ${failures} check(s) FAILED`);
process.exitCode = failures === 0 ? 0 : 1;
